### ISSUE TITLE
datadogAgentPort is Int making it impossible to supply environment variables

### ISSUE THREAD

**Issue by ivanoronee** [Colisweb/sbt-datadog#11]
<img width="397" alt="Screen Shot 2019-08-27 at 8 50 08 AM" src="https://user-images.githubusercontent.com/2422404/63786855-b697b500-c8a7-11e9-9dcd-a9bfc1f69480.png">

**Comment by guizmaii** [comment]
Hey @ivanoronee,

Good call. Thanks for the feedback. 

@sallareznov @tyrcho can you take a look please?

**Comment by tyrcho** [comment]
thanks, we'll have a look soon !

**Comment by tyrcho** [comment]
@gbogard when you have some time :)

**Comment by gbogard** [comment]
Hi @ivanoronee
Thank you for your feedback. The type of the datadogAgentPort key has been changed from `Int` to `String` in version 0.2.0.
