### ISSUE TITLE
Bintray is sunsetting on May 1st

### ISSUE THREAD

**Issue by aelesbao** [Colisweb/sbt-datadog#14]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

It would be great if the plugin could be published to another repository.

**Comment by LitlBro** [comment]
Hi, we are on our way to release to [maven](https://repo1.maven.org/maven2/com/colisweb/sbt-datadog_2.12_1.0/0.0.1/)
The latest release will be soon available

**Comment by LitlBro** [comment]
https://repo1.maven.org/maven2/com/colisweb/sbt-datadog_2.12_1.0/2.1.0/
now available :)

**Comment by guizmaii** [comment]
@LitlBro Can we close this issue then now?

**Comment by LitlBro** [comment]
yes, closing now

**Comment by guizmaii** [comment]
@LitlBro you need to update the README guys. It still mention Bintray. I'm too far from a computer right now, can't submit a PR, sorry.

**Comment by LitlBro** [comment]
thanks for spotting it, fixed.
