### ISSUE TITLE
Support setting parameters at runtime

### ISSUE THREAD

**Issue by keirlawson** [Colisweb/sbt-datadog#21]
I'm not sure if this could even be possible/appropriate but thought I'd flag it as an idea:

My service will not know the datadog agent host/port and also the env until runtime as it reads these values from environment variables when deployed, whereas this plugin currently relies on them being set at build time.  It would be great if there could be some way to accommodate setting some of these at runtime?

**Comment by guizmaii** [comment]
Hi @keirlawson,

I think what you're looking for is already possible and already explained in the documentation.

See https://github.com/Colisweb/sbt-datadog#datadogagenthost
