### ISSUE TITLE
sbt 0.13 support

### ISSUE THREAD

**Issue by gjsduarte** [Colisweb/sbt-datadog#8]
Hi, it would be great for this library to support sbt 0.13.
If you create a branch for it I can make PR from my fork, where I have already implemented support for it.

**Comment by guizmaii** [comment]
HI @gjsduarte,

Sorry for the delay, I just saw your issue.

Can you propose a PR plz ?

**Comment by gjsduarte** [comment]
Yeah, sure... but I think it would be better if you open a branch first, as I can only PR to existing branches. Or do you want me to open the PR to master?

**Comment by guizmaii** [comment]
PR to master is ok.
